janis_bioinformatics/tools/bcftools/norm/base.py, janis_bioinformatics/tools/gatk4/filtermutectcalls/base.py, janis_bioinformatics/tools/gatk4/learnreadorientationmodel/base.py, janis_bioinformatics/tools/gatk4/mutect2/base_4_1.py
Changed default memory for tools to not crash
changed output file extension to vcf.gz for filter output
changed normalisation step to split up multi allelic sites
=> Api review

janis_bioinformatics/tools/illumina/strelkasomatic/base.py
Changed the input type of two options to be VcfTabix instead of File
=> forceGT requires tabix index

janis_bioinformatics/tools/__init__.py, janis_bioinformatics/tools/vcflib/__init__.py, janis_bioinformatics/tools/vcflib/vcfallelicprimitives/base.py, janis_bioinformatics/tools/vcflib/vcfallelicprimitives/versions.py, janis_bioinformatics/tools/vcflib/vcffixup/base.py, janis_bioinformatics/tools/vcflib/vcffixup/versions.py, janis_bioinformatics/tools/vcflib/vcflib_1_0_1.py, janis_bioinformatics/tools/vcflib/vcflibtoolbase.py, janis_bioinformatics/tools/vcflib/vcfrandomsample/base.py, janis_bioinformatics/tools/vcflib/vcfrandomsample/versions.py, janis_bioinformatics/tools/vcflib/vcfroc/base.py, janis_bioinformatics/tools/vcflib/vcfroc/versions.py, janis_bioinformatics/tools/vcflib/vcfuniq/base.py, janis_bioinformatics/tools/vcflib/vcfuniq/versions.py, janis_bioinformatics/tools/vcflib/vcfuniqalleles/base.py, janis_bioinformatics/tools/vcflib/vcfuniqalleles/versions.py
This commit contains all tools required to run freebayes in parallel.
There are more tools in vcflib, but they overlap with bcftools or 
picard, so I will wrap them when needed
=> initial commit of the vcflib wrappers

janis_bioinformatics/data_types/__init__.py, janis_bioinformatics/data_types/crai.py, janis_bioinformatics/data_types/cram.py
cram with the same structure as bams
=> added cram file types

janis_bioinformatics/tools/bwa/mem/base.py
No idea if this is tested, but shouldn't BWA get an index in stead of a fasta reference?
If this checks out, feel free to merge. If not, just close it again.
Cheers
M
=> fix bwa reference

janis_bioinformatics/tools/bwa/mem/base.py
bwa input can also be non paired end.
M
=> change bwa input from fq pair to fq array

janis_bioinformatics/tools/samtools/view/base.py
=> Add region argument to SamtoolsView

janis_bioinformatics/tools/samtools/sort/base.py
=> Comment out the unused temporaryOutputs output on samtoolssort

janis_bioinformatics/tools/illumina/__init__.py, janis_bioinformatics/tools/illumina/bcl2fastq/base.py, janis_bioinformatics/tools/illumina/bcl2fastq/versions.py
In progress
It seems the illumina tools use a slightly other mechanism to register than the other tools, but other than that, ready to go IMO.
Cheers
M
=> WIP - new tool: bcl2fastq

janis_bioinformatics/tools/__init__.py, janis_bioinformatics/tools/kallisto/__init__.py, janis_bioinformatics/tools/kallisto/data_types.py, janis_bioinformatics/tools/kallisto/index/base.py, janis_bioinformatics/tools/kallisto/index/versions.py, janis_bioinformatics/tools/kallisto/quant/base.py, janis_bioinformatics/tools/kallisto/quant/versions.py, janis_bioinformatics/tools/kallisto/versions.py
A basic integration of kallisto.
It doesn't currently support the pseudo* outputs or the single cell stuff, but they should really be separate commands.
=> add a basic integration of kallisto.

janis_bioinformatics/tools/gatk4/mutect2/base_4_1.py
Closes https://github.com/PMCC-BioinformaticsCore/janis-bioinformatics/issues/40
=> Make mutect2 normal inputs optional per spec

janis_bioinformatics/tools/freebayes/base_1_3_cram.py, janis_bioinformatics/tools/gatk4/getpileupsummaries/base_cram.py, janis_bioinformatics/tools/gatk4/mutect2/base_4_1_cram.py, janis_bioinformatics/tools/illumina/manta/base_cram.py, janis_bioinformatics/tools/illumina/strelkasomatic/base_cram.py, janis_bioinformatics/utils/typeconversion.py
Based on comments in https://github.com/PMCC-BioinformaticsCore/janis-bioinformatics/pull/13#pullrequestreview-431585750.
=> Sebastian drawsontoolkit minorfixes

janis_bioinformatics/tools/__init__.py, janis_bioinformatics/tools/dawson/workflows/mutectjointsomaticworkflow.py, janis_bioinformatics/tools/whisper/__init__.py, janis_bioinformatics/tools/whisper/align/base.py, janis_bioinformatics/tools/whisper/align/versions.py, janis_bioinformatics/tools/whisper/data_types.py, janis_bioinformatics/tools/whisper/index/base.py, janis_bioinformatics/tools/whisper/index/versions.py, janis_bioinformatics/tools/whisper/versions.py
This is a basic integration. There are piles of extra options that I haven't attempted to incorporate.
=> Add whisper aligner

janis_bioinformatics/tools/dawson/dawsontoolkit_0_1.py, janis_bioinformatics/tools/dawson/workflows/strelka2passworkflow.py
This new version of the docker allows resolution of multiallelic variants from strelka2
also typecasting for nicer outputs
=> Update to latest docker container for dawsontoolkit and typecast for output

janis_bioinformatics/tools/dawson/workflows/strelka2passanalysisstep1.py, janis_bioinformatics/tools/dawson/workflows/strelka2passanalysisstep2.py, janis_bioinformatics/tools/dawson/workflows/strelka2passworkflow.py
strelka doesnt need anything but the indexed fasta, so relaxing requirements here
=> move to only fasta + fai

janis_bioinformatics/tools/pmac/extractstrelkasomaticaddp/versions.py, janis_bioinformatics/tools/pmac/versions.py, janis_bioinformatics/tools/variantcallers/illuminasomatic_strelka.py
Replace the version 0.1.0 with 0.1.1 because there's some bug in the 0.1.0 script
=> Replace PeterMacUtils version with 0.1.1

janis_bioinformatics/tools/babrahambioinformatics/fastqc/versions.py, janis_bioinformatics/tools/common/bwaaligner.py, janis_bioinformatics/tools/pmac/performanceSummaryTargetedWorkflow.py
Move the gatk4 related tools to version 4.1.2.0
=> Gatk version fix

janis_bioinformatics/tools/pmac/performanceSummaryTargetedWorkflow.py
Performance summary fix tool versions and add index bam step.
=> Performance summary fix

janis_bioinformatics/tools/ensembl/vep/v98_3/base.py
Tweak the output so you get a .txt suffix for the output filename.
=> make stdout a text file

janis_bioinformatics/tools/dawson/workflows/mutectjointsomaticworkflow.py, janis_bioinformatics/tools/gatk4/calculatecontaminations/versions.py, janis_bioinformatics/tools/gatk4/filtermutectcalls/versions.py, janis_bioinformatics/tools/gatk4/getpileupsummaries/versions.py, janis_bioinformatics/tools/gatk4/learnreadorientationmodel/versions.py, janis_bioinformatics/tools/gatk4/mergemutectstats/versions.py
setup the latest gatk versions
=> update versions for tools

janis_bioinformatics/tools/bcftools/__init__.py, janis_bioinformatics/tools/bcftools/annotate/versions.py, janis_bioinformatics/tools/bcftools/bcftools_1_5.py, janis_bioinformatics/tools/bcftools/bcftools_1_9.py, janis_bioinformatics/tools/bcftools/bcftoolstoolbase.py, janis_bioinformatics/tools/bcftools/concat/versions.py, janis_bioinformatics/tools/bcftools/fill_from_fasta/base.py, janis_bioinformatics/tools/bcftools/fill_from_fasta/versions.py, janis_bioinformatics/tools/bcftools/index/versions.py, janis_bioinformatics/tools/bcftools/norm/versions.py, janis_bioinformatics/tools/bcftools/sort/versions.py, janis_bioinformatics/tools/bcftools/versions.py, janis_bioinformatics/tools/bcftools/view/versions.py
Add a new tool in bcftools: fill-from-fasta
Clean up the versions in the bcftools
=> Bcftools update

janis_bioinformatics/tools/common/filtervardictsomaticvcf.py
Fix filter for vardict paired vcf, to remove variants with the tag " (STATUS=Germline)".
=> Fix vardict filter

janis_bioinformatics/tools/bcftools/concat/base.py
Set Bcftools concat input to UnionType
=> Set Bcftools concat input to UnionType

janis_bioinformatics/tools/samtools/mpileup/base.py
Samtools mpileup write to output file
=> Change samtools mpileup

janis_bioinformatics/tools/bcftools/view/base.py, janis_bioinformatics/tools/bedtools/coveragebed/base.py, janis_bioinformatics/tools/bedtools/genomecoveragebed/base.py, janis_bioinformatics/tools/bedtools/intersectbed/base.py, janis_bioinformatics/tools/common/__init__.py, janis_bioinformatics/tools/common/facetsWorkflow.py, janis_bioinformatics/tools/pmac/__init__.py, janis_bioinformatics/tools/pmac/circosplot/base.py, janis_bioinformatics/tools/pmac/gatherfilesformultiqc.py, janis_bioinformatics/tools/pmac/localisebambai.py, janis_bioinformatics/tools/pmac/localisefastawithdict.py, janis_bioinformatics/tools/pmac/localisefastqgzpair.py, janis_bioinformatics/tools/samtools/flagstat/base.py, janis_bioinformatics/tools/samtools/mpileup/base.py, janis_bioinformatics/tools/samtools/view/base.py, janis_bioinformatics/tools/samtools/view/view.py
New tools:
- LocaliseFastaWithDict
- LocaliseFastqGzPair
- LocaliseBamBai
Fix tools where output is stdout:
- bcftools view
- bedtools coveragebed
- bedtools genomecoveragebed
- bedtools intersectbed
- samtools flagstat
Update tool:
Circosplot
Update pmac version to rlupat/pmacutil:latest
=> Add new tools to localise files, and fixes tools with stdout output

README.md, janis_bioinformatics/tools/bedtools/intersectbed/base.py, janis_bioinformatics/tools/common/bwamem_samtoolsview.py, janis_bioinformatics/tools/dawson/createcallregions/base.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/freebayes/freebayessomaticworkflow.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/freebayes/freebayessomaticworkflow_cram.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/mutect2/mutect2jointsomaticworkflow.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/mutect2/mutect2jointsomaticworkflow_cram.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/strelka2/steps/strelka2passanalysisstep1.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/strelka2/steps/strelka2passanalysisstep1_cram.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/strelka2/steps/strelka2passanalysisstep2.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/strelka2/strelka2passworkflow.py, janis_bioinformatics/tools/dawson/workflows/variantcalling/multisample/strelka2/strelka2passworkflow_cram.py, janis_bioinformatics/tools/pmac/parsefastqc/v0_1_0.py, janis_bioinformatics/utils/typeconversion.py
Found one typo while reading the README, and spotted another one in a Python file. Used IDE-spellchecker to see if there were any others. One of the typos is actually in the code, so I will highlight it here for review.
=> Fix typos on README and python comments

.github/workflows/unit_tests.yml, janis_bioinformatics/__meta__.py, janis_bioinformatics/tools/bcftools/view/base.py, janis_bioinformatics/tools/common/indexfasta.py, janis_bioinformatics/tools/pmac/circosplot/base.py, tests/__init__.py
Merges all the changes and tools additions since late 2021. 
Update python dependencies
=> Release v0.12.1
